### ISSUE TITLE
Request for License

### ISSUE THREAD

**Issue by AerysL** [rbarazzutti/gitinfo2-latexmk#2]
This repo looks to be quite useful, however currently it is unlicensed. I would recommend adding a license (perhaps MIT, BSD, or whichever you find best suits your needs) to allow others (including myself) to use it in their projects. Thank you for your consideration.

Edit: Looking at gitinfo2 (which includes the example hook), it is under the The LATEX Project Public License 1.3, so that may be a good option for license if you choose to add one.

**Comment by rbarazzutti** [comment]
Thanks a lot for your suggestion. 

Let's use the `LaTeX project public license (LPPL), version 1.3c`
